---
title: "506hw3"
format: pdf
editor: visual
---

## Problem2

##a

```{r}
##install.packages("DBI")
##library(DBI)
##install.packages("RSQLite")
##library(RSQLite)
sakila <- dbConnect(RSQLite::SQLite(), "~/Downloads/sakila_master.db")
##dbListTables(sakila)
```

##a

```{r}
dbGetQuery(sakila,"SELECT language_id, COUNT(*) as film_count
FROM film
GROUP BY language_id
ORDER BY film_count DESC
LIMIT 1 OFFSET 1")
```

##b

```{r}
dbGetQuery(sakila, "SELECT category_id, COUNT (*) as cat_count
FROM film_category
GROUP BY category_id
ORDER BY cat_count
LIMIT 1")
```

##c

```{r}
dbGetQuery(sakila, "SELECT country, COUNT(customer_id) as cust_count
FROM customer
JOIN address ON customer.address_id = address.address_id
JOIN city ON address.city_id = city.city_id
JOIN country ON city.country_id = country.country_id
GROUP BY country
HAVING cust_count = 9")

```

## Problem3

```{r}
library(readr)
us_500 <- read_csv("~/Downloads/us-500.csv")
##View(us_500)
```

##a

```{r}
pat<-"\\.net"
li<-grep(pat,us_500$email)
length(li)/length(us_500$email)
```

##b

```{r}
pat1<-"[^A-za-z0-9@]"
lis<-grep(pat1,us_500$email)
length(lis)/length(us_500$email)
```

##c

```{r}
##install.packages("stringr")
library(stringr)
```

```{r}
phonenum<-c(us_500$phone1,us_500$phone2)
areacode<-str_extract(phonenum,"[0-9]{3}")
code_count<-table(areacode)
names(table(areacode))[which.max(code_count)]
```

##d

```{r}
stnum<-str_extract(us_500$address,"#(\\d*)$")
stnum1<-stnum[!is.na(stnum)]
stnum2<-gsub("#", "", stnum1)
stnum3<-log(as.numeric(stnum2))
hist(stnum3, main = "Histogram of Log Apartment Numbers", xlab = "Log Apartment Numbers")
```

##e

```{r}

```

##f

```{r}

```
